TRUNCATE TABLE office_hours_entries;
INSERT INTO office_hours_entries (faculty, department, email, office, day, start, "end", type) VALUES
('Dr. Mariam Biltawi', 'Computer Science', 'mariam.biltawi@htu.edu.jo', 'S-309', 'Saturday', '10:00', '11:30', 'In-Person'),
('Dr. Mariam Biltawi', 'Computer Science', 'mariam.biltawi@htu.edu.jo', 'S-309', 'Sunday', '11:30', '01:00', 'In-Person'),
('Dr. Mariam Biltawi', 'Computer Science', 'mariam.biltawi@htu.edu.jo', 'S-309', 'Sunday', '01:00', '02:00', 'In-Person'),
('Dr. Samir Tartir', 'Computer Science', 'samir.tartir@gmail.com', 'S-324', 'Monday', '2:00', '2:30', 'In-Person'),
('Dr. Samir Tartir', 'Computer Science', 'samir.tartir@gmail.com', 'S-324', 'Tuesday', '12:00', '1:00', 'In-Person'),
('Dr. Samir Tartir', 'Computer Science', 'samir.tartir@gmail.com', 'S-324', 'Thursday', '13:30', '15:30', 'In-Person'),
('Dr. Samir Tartir', 'Computer Science', 'samir.tartir@gmail.com', 'S-324', 'Saturday', '12:00', '1:00', 'In-Person'),
('Dr. Samir Tartir', 'Computer Science', 'samir.tartir@gmail.com', 'S-324', 'Tuesday', '4:00', '4:30', 'In-Person'),
('Dr. Rami Al-Ouran', 'Data Science and AI', 'rami.alouran@htu.edu.jo', 'S-314', 'Sunday', '11:30am', '12:30pm', 'In-Person'),
('Dr. Rami Al-Ouran', 'Data Science and AI', 'rami.alouran@htu.edu.jo', 'S-314', 'Monday', '11:30am', '12:30pm', 'In-Person'),
('Dr. Rami Al-Ouran', 'Data Science and AI', 'rami.alouran@htu.edu.jo', 'S-314', 'Wednesday', '11:30am', '12:30pm', 'In-Person'),
('Dr. Rami Al-Ouran', 'Data Science and AI', 'rami.alouran@htu.edu.jo', 'S-314', 'Thursday', '11:30am', '12:30pm', 'In-Person'),
('Dr. Raneem Qaddoura', 'Data Science and Artificial Intelligence', 'raneem.qaddoura@htu.edu.jo', 'S-309', 'Saturday', '8:30', '10:00', 'In-Person'),
('Dr. Raneem Qaddoura', 'Data Science and Artificial Intelligence', 'raneem.qaddoura@htu.edu.jo', 'S-309', 'Sunday', '10:00', '11:30', 'In-Person'),
('Dr. Raneem Qaddoura', 'Data Science and Artificial Intelligence', 'raneem.qaddoura@htu.edu.jo', 'S-309', 'Monday', '11:30', '13:00', 'In-Person'),
('Dr. Raneem Qaddoura', 'Data Science and Artificial Intelligence', 'raneem.qaddoura@htu.edu.jo', 'S-309', 'Tuesday', '13:00', '14:30', 'In-Person'),
('Dr. Raneem Qaddoura', 'Data Science and Artificial Intelligence', 'raneem.qaddoura@htu.edu.jo', 'S-309', 'Thursday', '14:30', '16:00', 'In-Person'),
('Dr. Raneem Qaddoura', 'Data Science and Artificial Intelligence', 'raneem.qaddoura@htu.edu.jo', 'S-309', 'Thursday', '16:30', '17:30', 'In-Person'),
('Murad Yaghi', 'Data Science and Artificial Intelligence', 'murad.yaghi@htu.edu.jo', 'S-322', 'Saturday', '14:30', '15:30', 'In-Person'),
('Murad Yaghi', 'Data Science and Artificial Intelligence', 'murad.yaghi@htu.edu.jo', 'S-322', 'Sunday', '17:30', '18:30', 'In-Person'),
('Dr. Salem Alemaishat - Spring 2026 Office Hours', 'Computer Science', 'salem.alemaishat@htu.edu.jo', 'S-323', 'Sunday', '1:00pm', '1:30pm', 'In-Person'),
('Dr. Salem Alemaishat - Spring 2026 Office Hours', 'Computer Science', 'salem.alemaishat@htu.edu.jo', 'S-323', 'Wednesday', '1:00pm', '1:30pm', 'In-Person'),
('Dr. Salem Alemaishat - Spring 2026 Office Hours', 'Computer Science', 'salem.alemaishat@htu.edu.jo', 'S-323', 'Thursday', '2:30pm', '3:00pm', 'In-Person'),
('Abdulrahman Abu Alfoul', 'AI & Data Science', 'Abdulrahman.aboalfoul@HTU.EDU.JO', 'W-214', 'Saturday', '10:00', '11:00', 'In-Person'),
('Abdulrahman Abu Alfoul', 'AI & Data Science', 'Abdulrahman.aboalfoul@HTU.EDU.JO', 'W-214', 'Sunday', '12:00', '1:00', 'In-Person'),
('Abdulrahman Abu Alfoul', 'AI & Data Science', 'Abdulrahman.aboalfoul@HTU.EDU.JO', 'W-214', 'Monday', '1:00', '2:00', 'In-Person'),
('Ashraf Alsmadi', 'computer science', 'ashraf.al-smadi@htu.edu.jo', 'S310', 'Saturday', '13:00', '14:30', 'In-Person'),
('Ashraf Alsmadi', 'computer science', 'ashraf.al-smadi@htu.edu.jo', 'S310', 'Sunday', '14:00', '17:00', 'In-Person'),
('Ashraf Alsmadi', 'computer science', 'ashraf.al-smadi@htu.edu.jo', 'S310', 'Tuesday', '14:30', '16:00', 'In-Person'),
('Ashraf Alsmadi', 'computer science', 'ashraf.al-smadi@htu.edu.jo', 'S310', 'Wednesday', '16:00', '17:30', 'In-Person'),
('Asma Al-Fakhore', 'Data Science and Artificial Intelligence', 'asma.alfakhore@htu.edu.jo', 'IJC-04', 'Saturday', '10:00', '11:30', 'In-Person'),
('Asma Al-Fakhore', 'Data Science and Artificial Intelligence', 'asma.alfakhore@htu.edu.jo', 'IJC-04', 'Sunday', '11:30', '1:00', 'In-Person'),
('Asma Al-Fakhore', 'Data Science and Artificial Intelligence', 'asma.alfakhore@htu.edu.jo', 'IJC-04', 'Monday', '1:00', '2:30', 'In-Person'),
('Asma Al-Fakhore', 'Data Science and Artificial Intelligence', 'asma.alfakhore@htu.edu.jo', 'IJC-04', 'Tuesday', '2:30', '4:00', 'In-Person'),
('Eng. Asmaa Lafi', 'Cyber Security', 'asmaa.lafi@htu.edu.jo', 'S-313', 'Saturday', '12:00', '1:00', 'In-Person'),
('Ayah karajah', 'Data science and Artificial intelligence', 'Ayah.karajeh@htu.edu.jo', 'S312', 'Saturday', '10:00', '11:30', 'In-Person'),
('Ayah karajah', 'Data science and Artificial intelligence', 'Ayah.karajeh@htu.edu.jo', 'S312', 'Sunday', '1:00', '1:30', 'In-Person'),
('Ayah karajah', 'Data science and Artificial intelligence', 'Ayah.karajeh@htu.edu.jo', 'S312', 'Monday', '10:00', '11:30', 'In-Person'),
('Ayah karajah', 'Data science and Artificial intelligence', 'Ayah.karajeh@htu.edu.jo', 'S312', 'Tuesday', '1:00', '1:30', 'In-Person'),
('Israa Ibrahim Ismael Hasan', 'Cyber security', 'Israa.hasan@htu.edu.jo', '321', 'Sunday', '10:30', '11:30', 'In-Person'),
('Israa Ibrahim Ismael Hasan', 'Cyber security', 'Israa.hasan@htu.edu.jo', '321', 'Monday', '10:30', '11:30', 'In-Person'),
('Israa Ibrahim Ismael Hasan', 'Cyber security', 'Israa.hasan@htu.edu.jo', '321', 'Wednesday', '10:30', '11:30', 'In-Person'),
('Israa Ibrahim Ismael Hasan', 'Cyber security', 'Israa.hasan@htu.edu.jo', '321', 'Thursday', '10:30', '11:30', 'In-Person'),
('Malek Allouzi', 'Computer Science', 'Malik.Louzi@htu.edu.jo', 'S-310', 'Monday', '10:00', '11:30', 'In-Person'),
('Malek Allouzi', 'Computer Science', 'Malik.Louzi@htu.edu.jo', 'S-310', 'Tuesday', '10:00', '11:30', 'In-Person'),
('Malek Allouzi', 'Computer Science', 'Malik.Louzi@htu.edu.jo', 'S-310', 'Thursday', '10:00', '11:30', 'In-Person'),
('Malek Allouzi', 'Computer Science', 'Malik.Louzi@htu.edu.jo', 'S-310', 'Saturday', '10:00', '11:30', 'In-Person'),
('Malek Allouzi', 'Computer Science', 'Malik.Louzi@htu.edu.jo', 'S-310', 'Wednesday', '1:00', '1:30', 'In-Person'),
('Malek Allouzi', 'Computer Science', 'Malik.Louzi@htu.edu.jo', 'S-310', 'Sunday', '1:00', '1:30', 'In-Person'),
('Reem BaniHani', 'CS', 'reem.banihani@htu.edu.jo', 'S-311', 'Thursday', '12:30', '1:30', 'In-Person'),
('Reem BaniHani', 'CS', 'reem.banihani@htu.edu.jo', 'S-311', 'Thursday', '1:30', '2:30', 'In-Person'),
('Ro’aa Almomani', 'Computer Science', 'Roaa.Almomani@HTU.EDU.JO', '4', 'Saturday', '10:00', '11:00', 'In-Person'),
('Ro’aa Almomani', 'Computer Science', 'Roaa.Almomani@HTU.EDU.JO', '4', 'Sunday', '10:00', '11:00', 'In-Person'),
('Ro’aa Almomani', 'Computer Science', 'Roaa.Almomani@HTU.EDU.JO', '4', 'Monday', '1:00', '2:00', 'In-Person'),
('Sama Hamza', 'Data Science and Artificial Intelligence', 'sama.hamza@htu.edu.jo', 'S-315', 'Saturday', '12:00', '13:00', 'In-Person'),
('Sama Hamza', 'Data Science and Artificial Intelligence', 'sama.hamza@htu.edu.jo', 'S-315', 'Sunday', '10:00', '11:00', 'In-Person'),
('Sama Hamza', 'Data Science and Artificial Intelligence', 'sama.hamza@htu.edu.jo', 'S-315', 'Monday', '13:00', '14:00', 'In-Person'),
('Sami Aqeel Murshed Almashaqbeh', 'Cyber Security', 'sami.al-mashaqbeh@htu.edu.jo', 'S-310', 'Saturday', '8:30', '10:00', 'In-Person'),
('Sami Aqeel Murshed Almashaqbeh', 'Cyber Security', 'sami.al-mashaqbeh@htu.edu.jo', 'S-310', 'Thursday', '10:00', '11:30', 'In-Person'),
('Sami Aqeel Murshed Almashaqbeh', 'Cyber Security', 'sami.al-mashaqbeh@htu.edu.jo', 'S-310', 'Thursday', '11:30', '01:00', 'In-Person'),
('Sami Aqeel Murshed Almashaqbeh', 'Cyber Security', 'sami.al-mashaqbeh@htu.edu.jo', 'S-310', 'Thursday', '01:00', '2:30', 'In-Person'),
('Sami Aqeel Murshed Almashaqbeh', 'Cyber Security', 'sami.al-mashaqbeh@htu.edu.jo', 'S-310', 'Thursday', '02:30', '17:59', 'In-Person'),
('Sara Falah Mohammad Abdo', 'Computer Science', 'Sara.Abdo@htu.edu.jo', 'S-315', 'Saturday', '11:00', '1:00', 'In-Person'),
('Sara Falah Mohammad Abdo', 'Computer Science', 'Sara.Abdo@htu.edu.jo', 'S-315', 'Monday', '12:00', '1:00', 'In-Person'),
('Eng. Weaam Alrbeiqi', 'Cyber Security', 'Weaam.Alrbeiqi@htu.edu.jo', 's-320', 'Saturday', '8:30', '10:00', 'In-Person'),
('Eng. Weaam Alrbeiqi', 'Cyber Security', 'Weaam.Alrbeiqi@htu.edu.jo', 's-320', 'Thursday', '11:30', '1:00', 'In-Person'),
('Eng. Weaam Alrbeiqi', 'Cyber Security', 'Weaam.Alrbeiqi@htu.edu.jo', 's-320', 'Thursday', '2:30', '4:00', 'In-Person'),
('Yazan Al-Shannik', 'Cyber Security', 'Yazan.alshannik@htu.edu.jo', 'W-B05', 'Monday', '09:00', '10:00', 'In-Person'),
('Yazan Al-Shannik', 'Cyber Security', 'Yazan.alshannik@htu.edu.jo', 'W-B05', 'Thursday', '09:00', '10:00', 'In-Person'),
('Yazan Al-Shannik', 'Cyber Security', 'Yazan.alshannik@htu.edu.jo', 'W-B05', 'Wednesday', '01:30', '02:30', 'In-Person'),
('Yazan Al-Shannik', 'Cyber Security', 'Yazan.alshannik@htu.edu.jo', 'W-B05', 'Sunday', '01:30', '02:30', 'In-Person'),
('Batool Alarmouti', 'Data Science and Artificial Intelligence', 'batool.alarmouti@htu.edu.jo', 'S-320', 'Saturday', '08:30', '10:00', 'In-Person'),
('Batool Alarmouti', 'Data Science and Artificial Intelligence', 'batool.alarmouti@htu.edu.jo', 'S-320', 'Tuesday', '10:00', '11:30', 'In-Person'),
('Batool Alarmouti', 'Data Science and Artificial Intelligence', 'batool.alarmouti@htu.edu.jo', 'S-320', 'Thursday', '11:30', '01:00', 'In-Person'),
('Batool Alarmouti', 'Data Science and Artificial Intelligence', 'batool.alarmouti@htu.edu.jo', 'S-320', 'Thursday', '01:00', '02:30', 'In-Person'),
('Batool Alarmouti', 'Data Science and Artificial Intelligence', 'batool.alarmouti@htu.edu.jo', 'S-320', 'Thursday', '02:30', '04:00', 'In-Person'),
('Aman Aloudat', 'Cybersecurity', 'aman.aloudat@htu.edu.jo', 'S-321', 'Saturday', '10:00', '11:00', 'In-Person'),
('Aman Aloudat', 'Cybersecurity', 'aman.aloudat@htu.edu.jo', 'S-321', 'Sunday', '10:00', '11:00', 'In-Person'),
('Aman Aloudat', 'Cybersecurity', 'aman.aloudat@htu.edu.jo', 'S-321', 'Monday', '10:00', '11:00', 'In-Person'),
('Aman Aloudat', 'Cybersecurity', 'aman.aloudat@htu.edu.jo', 'S-321', 'Tuesday', '10:00', '11:00', 'In-Person'),
('Asma Mohammad Sabbah', 'Computer Science', 'asma.sabbah@htu.edu.jo', 'S-311', 'Sunday', '8:30', '10:00', 'In-Person'),
('Asma Mohammad Sabbah', 'Computer Science', 'asma.sabbah@htu.edu.jo', 'S-311', 'Wednesday', '10:00', '11:30', 'In-Person'),
('Asma Mohammad Sabbah', 'Computer Science', 'asma.sabbah@htu.edu.jo', 'S-311', 'Saturday', '11:30', '1:00', 'In-Person'),
('Asma Mohammad Sabbah', 'Computer Science', 'asma.sabbah@htu.edu.jo', 'S-311', 'Saturday', '01:00', '2:30', 'In-Person'),
('Asma Mohammad Sabbah', 'Computer Science', 'asma.sabbah@htu.edu.jo', 'S-311', 'Saturday', '2:30', '4:00', 'In-Person'),
('Razan AlQuraan', 'Computer Science', 'razan.alquran@htu.edu.jo', 'S-313', 'Saturday', '12:00', '1:00', 'In-Person'),
('Razan AlQuraan', 'Computer Science', 'razan.alquran@htu.edu.jo', 'S-313', 'Tuesday', '1:00', '2:30', 'In-Person'),
('Razan AlQuraan', 'Computer Science', 'razan.alquran@htu.edu.jo', 'S-313', 'Thursday', '2:30', '4:00', 'In-Person'),
('Razan AlQuraan', 'Computer Science', 'razan.alquran@htu.edu.jo', 'S-313', 'Thursday', '4:00', '5:00', 'In-Person'),
('Shatha Ali Al hawawsheh', 'Computer Science', 'shatha.alhawawsheh@htu.edu.jo', 'S-213', 'Saturday', '8:30', '10:00', 'In-Person'),
('Shatha Ali Al hawawsheh', 'Computer Science', 'shatha.alhawawsheh@htu.edu.jo', 'S-213', 'Sunday', '10:00', '11:30', 'In-Person'),
('Shatha Ali Al hawawsheh', 'Computer Science', 'shatha.alhawawsheh@htu.edu.jo', 'S-213', 'Monday', '11:30', '12:30', 'In-Person'),
('Shatha Ali Al hawawsheh', 'Computer Science', 'shatha.alhawawsheh@htu.edu.jo', 'S-213', 'Tuesday', '11:30', '01:30', 'In-Person'),
('Shatha Ali Al hawawsheh', 'Computer Science', 'shatha.alhawawsheh@htu.edu.jo', 'S-213', 'Wednesday', '2:30', '4:00', 'In-Person'),
('As’har Khamaiseh (أسحار)', 'Cyber Security', 'ashar.khamaiseh@htu.edu.jo', 'S-311', 'Saturday', '1:00', '2:00', 'In-Person'),
('Bassam Kasasbeh', 'Data Science and Artificial Intelligence', 'bassam.alkasasbeh@htu.edu.jo', 'S-310', 'Saturday', '9:00', '10:00', 'In-Person'),
('Bassam Kasasbeh', 'Data Science and Artificial Intelligence', 'bassam.alkasasbeh@htu.edu.jo', 'S-310', 'Sunday', '10:00', '11:30', 'In-Person'),
('Bassam Kasasbeh', 'Data Science and Artificial Intelligence', 'bassam.alkasasbeh@htu.edu.jo', 'S-310', 'Wednesday', '11:30', '13:00', 'In-Person'),
('Bassam Kasasbeh', 'Data Science and Artificial Intelligence', 'bassam.alkasasbeh@htu.edu.jo', 'S-310', 'Wednesday', '13:00', '14:30', 'In-Person'),
('Bassam Kasasbeh', 'Data Science and Artificial Intelligence', 'bassam.alkasasbeh@htu.edu.jo', 'S-310', 'Wednesday', '14:30', '15:30', 'In-Person'),
('Hana AlRasheed', 'Computer Science', 'hana.alrasheed@htu.edu.jo', 'S312', 'Monday', '10:00', '11:00', 'In-Person'),
('Hana AlRasheed', 'Computer Science', 'hana.alrasheed@htu.edu.jo', 'S312', 'Tuesday', '11:00', '12:00', 'In-Person'),
('Hana AlRasheed', 'Computer Science', 'hana.alrasheed@htu.edu.jo', 'S312', 'Thursday', '10:00', '11:00', 'In-Person'),
('Hana AlRasheed', 'Computer Science', 'hana.alrasheed@htu.edu.jo', 'S312', 'Saturday', '11:00', '12:00', 'In-Person'),
('Orwah Mohammad Aladaileh', 'Computer Science', 'orwa.aladaileh@htu.edu.jo', 'Time/Day:', 'Monday', '01:00', '02:00', 'In-Person'),
('Orwah Mohammad Aladaileh', 'Computer Science', 'orwa.aladaileh@htu.edu.jo', 'Time/Day:', 'Tuesday', '11:30', '02:00', 'In-Person'),
('Orwah Mohammad Aladaileh', 'Computer Science', 'orwa.aladaileh@htu.edu.jo', 'Time/Day:', 'Thursday', '01:00', '02:00', 'In-Person'),
('Suhaib Ghazi Al-Obeidallah', 'Computer Science', 'suhaib.alobeidallah@htu.edu.jo', 'W-214', 'Saturday', '13:00', '14:00', 'In-Person'),
('Suhaib Ghazi Al-Obeidallah', 'Computer Science', 'suhaib.alobeidallah@htu.edu.jo', 'W-214', 'Sunday', '10:00', '11:00', 'In-Person'),
('Suhaib Ghazi Al-Obeidallah', 'Computer Science', 'suhaib.alobeidallah@htu.edu.jo', 'W-214', 'Monday', '10:00', '11:00', 'In-Person'),
('Suhaib Ghazi Al-Obeidallah', 'Computer Science', 'suhaib.alobeidallah@htu.edu.jo', 'W-214', 'Tuesday', '10:00', '11:00', 'In-Person'),
('Sultan Alrushdan', 'Computer Science', 'sultan.alrushdan@htu.edu.jo', 'S-308', 'Saturday', '08:30', '10:00', 'In-Person'),
('Sultan Alrushdan', 'Computer Science', 'sultan.alrushdan@htu.edu.jo', 'S-308', 'Tuesday', '10:00', '11:30', 'In-Person'),
('Sultan Alrushdan', 'Computer Science', 'sultan.alrushdan@htu.edu.jo', 'S-308', 'Thursday', '11:30', '01:00', 'In-Person'),
('Sultan Alrushdan', 'Computer Science', 'sultan.alrushdan@htu.edu.jo', 'S-308', 'Thursday', '01:00', '02:30', 'In-Person'),
('Elham Mahmoud Derbas', 'cyber security', 'Elham.derbas@htu.edu.jo', 'S321', 'Saturday', '9:00', '10:00', 'In-Person'),
('Elham Mahmoud Derbas', 'cyber security', 'Elham.derbas@htu.edu.jo', 'S321', 'Sunday', '12:00', '1:00', 'In-Person'),
('Eng MalakFraihat', 'Unknown', '', '', '', '', '', 'In-Person'),
('Mohammad NoorAldeen Alkhateeb', 'CS', 'mohammad.alkhateeb@htu.edu.jo', 'W-214', 'Saturday', '11:30', '12:30', 'In-Person'),
('Mohammad NoorAldeen Alkhateeb', 'CS', 'mohammad.alkhateeb@htu.edu.jo', 'W-214', 'Thursday', '10:30', '11:30', 'In-Person'),
('Eng. Ibrahim Ghanem', 'Cybersecurity', 'Ibrahim.ghanem@htu.edu.jo', 'Eiman Building | IJC-07', 'Saturday', '2:30', '4:00', 'In-Person'),
('Eng. Ibrahim Ghanem', 'Cybersecurity', 'Ibrahim.ghanem@htu.edu.jo', 'Eiman Building | IJC-07', 'Thursday', '1:00', '2:30', 'In-Person'),
('Qutaiba Albluwi', 'Cybersecurity', 'qutaiba.albluwi@htu.edu.jo', 'Dean''s Office (S-319)', 'Wednesday', '10:00', '10:30', 'In-Person'),
('Qutaiba Albluwi', 'Cybersecurity', 'qutaiba.albluwi@htu.edu.jo', 'Dean''s Office (S-319)', 'Tuesday', '10:00', '10:30', 'In-Person'),
('Mohammad Yahia', 'Computer Science', 'mohammad.yahia@htu.edu.jo', 'S-318', 'Sunday', '11:30', '12:30', 'In-Person'),
('Mohammad Yahia', 'Computer Science', 'mohammad.yahia@htu.edu.jo', 'S-318', 'Monday', '11:30', '12:30', 'In-Person'),
('Mohammad Yahia', 'Computer Science', 'mohammad.yahia@htu.edu.jo', 'S-318', 'Tuesday', '11:30', '12:30', 'In-Person'),
('Mohammad Yahia', 'Computer Science', 'mohammad.yahia@htu.edu.jo', 'S-318', 'Wednesday', '11:30', '12:30', 'In-Person'),
('Banan Mohammad Khanfar', 'Cyber Security', 'banan.khanfar@htu.edu.jo', 'S-315', 'Sunday', '8:30', '10:00', 'In-Person'),
('Banan Mohammad Khanfar', 'Cyber Security', 'banan.khanfar@htu.edu.jo', 'S-315', 'Monday', '10:00', '11:30', 'In-Person'),
('Banan Mohammad Khanfar', 'Cyber Security', 'banan.khanfar@htu.edu.jo', 'S-315', 'Tuesday', '11:30', '13:00', 'In-Person'),
('Banan Mohammad Khanfar', 'Cyber Security', 'banan.khanfar@htu.edu.jo', 'S-315', 'Wednesday', '13:00', '14:30', 'In-Person'),
('Banan Mohammad Khanfar', 'Cyber Security', 'banan.khanfar@htu.edu.jo', 'S-315', 'Thursday', '14:30', '16:00', 'In-Person'),
('Balqees Aldabaybeh', 'SCI', 'Balqis.aldabaibeh@htu.edu.jo', 'S320', 'Saturday', '1:30', '2:30', 'In-Person'),
('Balqees Aldabaybeh', 'SCI', 'Balqis.aldabaibeh@htu.edu.jo', 'S320', 'Sunday', '1:30', '3:30', 'In-Person');